<?php

namespace Tests\Unit\Domain\Repositories\Command;

use Tests\Stubs\Repositories\Command\CareerRepStub;
use Tests\Unit\Domain\Repositories\BaseRepositoryTestCase;
use App\Core\Domain\Repositories\Command\Misc\CareerRepInterface;
use App\Core\Domain\Entities\Career;
use PHPUnit\Framework\Attributes\Test;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class CareerRepInterfaceTest extends BaseRepositoryTestCase
{
    /**
     * The interface class being implemented
     */
    protected string $interfaceClass = CareerRepInterface::class;

    /**
     * Setup the repository instance for testing
     */
    protected function setUp(): void
    {
        parent::setUp();

        // Usamos un stub para probar el contrato
        $this->repository = new CareerRepStub();
    }

    /**
     * Test que el repositorio puede ser instanciado
     */
    #[Test]
    public function it_can_be_instantiated(): void
    {
        $this->assertNotNull($this->repository, 'El repositorio no está inicializado');
        $this->assertImplementsInterface($this->interfaceClass);
    }

    /**
     * Test que todos los métodos requeridos existen
     */
    #[Test]
    public function it_has_all_required_methods(): void
    {
        $this->assertNotNull($this->repository, 'El repositorio no está inicializado');

        $methods = [
            'create',
            'delete',
            'update'
        ];

        foreach ($methods as $method) {
            $this->assertMethodExists($method);
        }
    }

    #[Test]
    public function it_can_create_career(): void
    {
        $career = new Career('Ingeniería en Sistemas');

        $result = $this->repository->create($career);

        $this->assertInstanceOf(Career::class, $result);
        $this->assertEquals('Ingeniería en Sistemas', $result->career_name);
        $this->assertNotNull($result->id);
        $this->assertIsInt($result->id);
    }

    #[Test]
    public function created_career_has_autogenerated_id(): void
    {
        $career = new Career('Medicina');

        $result = $this->repository->create($career);

        $this->assertNotNull($result->id);
        $this->assertGreaterThan(0, $result->id);
    }

    #[Test]
    public function it_can_update_career(): void
    {
        // Primero crear una carrera
        $career = new Career('Arquitectura');
        $created = $this->repository->create($career);

        // Actualizar la carrera
        $fields = ['career_name' => 'Arquitectura y Diseño'];
        $result = $this->repository->update($created->id, $fields);

        $this->assertInstanceOf(Career::class, $result);
        $this->assertEquals($created->id, $result->id);
        $this->assertEquals('Arquitectura y Diseño', $result->career_name);
    }

    #[Test]
    public function update_throws_exception_when_career_not_found(): void
    {
        $careerId = 999; // ID que no existe
        $fields = ['career_name' => 'Nueva Carrera'];

        $this->expectException(ModelNotFoundException::class);

        $this->repository->update($careerId, $fields);
    }

    #[Test]
    public function update_can_handle_partial_fields(): void
    {
        // Primero crear una carrera
        $career = new Career('Derecho');
        $created = $this->repository->create($career);

        // Actualizar solo el nombre
        $fields = ['career_name' => 'Derecho Penal'];
        $result = $this->repository->update($created->id, $fields);

        $this->assertEquals('Derecho Penal', $result->career_name);
    }

    #[Test]
    public function it_can_delete_career(): void
    {
        // Primero crear una carrera
        $career = new Career('Psicología');
        $created = $this->repository->create($career);

        // Eliminar la carrera
        $this->repository->delete($created->id);

        // Verificar que ya no existe
        $stub = $this->repository;
        $this->expectException(ModelNotFoundException::class);

        // Intentar actualizar debería lanzar excepción
        $stub->update($created->id, ['career_name' => 'Psicología Clínica']);
    }

    #[Test]
    public function delete_throws_exception_when_career_not_found(): void
    {
        $careerId = 999; // ID que no existe

        $this->expectException(ModelNotFoundException::class);

        $this->repository->delete($careerId);
    }

    #[Test]
    public function create_preserves_existing_id_if_provided(): void
    {
        // Algunas implementaciones pueden permitir especificar el ID
        $career = new Career('Administración', 100);

        $result = $this->repository->create($career);

        // Depende de la implementación, podría usar el ID proporcionado o generar uno nuevo
        $this->assertInstanceOf(Career::class, $result);
        $this->assertEquals('Administración', $result->career_name);
    }

    #[Test]
    public function it_can_handle_multiple_operations(): void
    {
        $stub = new CareerRepStub();

        // 1. Crear carrera
        $career1 = $stub->create(new Career('Ingeniería Civil'));
        $this->assertInstanceOf(Career::class, $career1);
        $this->assertNotNull($career1->id);

        // 2. Actualizar carrera
        $updated = $stub->update($career1->id, ['career_name' => 'Ingeniería Civil y Ambiental']);
        $this->assertEquals('Ingeniería Civil y Ambiental', $updated->career_name);

        // 3. Crear otra carrera
        $career2 = $stub->create(new Career('Biología'));
        $this->assertNotNull($career2->id);
        $this->assertNotEquals($career1->id, $career2->id);

        // 4. Eliminar primera carrera
        $stub->delete($career1->id);

        // 5. Verificar que la primera ya no existe
        $this->expectException(ModelNotFoundException::class);
        $stub->update($career1->id, ['career_name' => 'Nuevo Nombre']);
    }

    #[Test]
    public function it_handles_database_errors_gracefully(): void
    {
        $stub = new CareerRepStub();
        $stub->shouldThrowDatabaseError(true);

        $career = new Career('Contabilidad');

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Database error');

        $stub->create($career);
    }

    #[Test]
    public function update_requires_valid_career_name(): void
    {
        // Primero crear una carrera
        $career = new Career('Enfermería');
        $created = $this->repository->create($career);

        // Actualizar con nombre vacío (depende de la validación)
        $fields = ['career_name' => ''];
        $result = $this->repository->update($created->id, $fields);

        // El stub debería permitir nombre vacío, pero podría validar en implementación real
        $this->assertEquals('', $result->career_name);
    }

    #[Test]
    public function career_name_is_required_for_creation(): void
    {
        // Esto depende de la validación en la implementación real
        // En el stub, debería funcionar
        $career = new Career('');
        $result = $this->repository->create($career);

        $this->assertInstanceOf(Career::class, $result);
        $this->assertEquals('', $result->career_name);
    }
}
