<?php

namespace Tests\Unit\Domain\Repositories\Command;

use Tests\Stubs\Repositories\Command\ParentInviteRepStub;
use Tests\Unit\Domain\Repositories\BaseRepositoryTestCase;
use App\Core\Domain\Repositories\Command\Misc\ParentInviteRepInterface;
use App\Core\Domain\Entities\ParentInvite;
use Carbon\Carbon;
use PHPUnit\Framework\Attributes\Test;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class ParentInviteRepInterfaceTest extends BaseRepositoryTestCase
{
    /**
     * The interface class being implemented
     */
    protected string $interfaceClass = ParentInviteRepInterface::class;

    /**
     * Setup the repository instance for testing
     */
    protected function setUp(): void
    {
        parent::setUp();

        // Usamos un stub para probar el contrato
        $this->repository = new ParentInviteRepStub();
    }

    /**
     * Test que el repositorio puede ser instanciado
     */
    #[Test]
    public function it_can_be_instantiated(): void
    {
        $this->assertNotNull($this->repository, 'El repositorio no está inicializado');
        $this->assertImplementsInterface($this->interfaceClass);
    }

    /**
     * Test que todos los métodos requeridos existen
     */
    #[Test]
    public function it_has_all_required_methods(): void
    {
        $this->assertNotNull($this->repository, 'El repositorio no está inicializado');

        $methods = [
            'create',
            'markAsUsed',
            'deleteExpired'
        ];

        foreach ($methods as $method) {
            $this->assertMethodExists($method);
        }
    }

    #[Test]
    public function it_can_create_parent_invite(): void
    {
        $invite = new ParentInvite(
            studentId: 1,
            email: 'parent@example.com',
            token: 'unique_token_123',
            expiresAt: Carbon::now()->addDays(7),
            createdBy: 2
        );

        $result = $this->repository->create($invite);

        $this->assertInstanceOf(ParentInvite::class, $result);
        $this->assertEquals('parent@example.com', $result->email);
        $this->assertEquals('unique_token_123', $result->token);
        $this->assertNotNull($result->id);
        $this->assertNull($result->usedAt); // No usado al crear
    }

    #[Test]
    public function created_invite_has_autogenerated_id(): void
    {
        $invite = new ParentInvite(
            studentId: 3,
            email: 'test@example.com',
            token: 'token_456',
            expiresAt: Carbon::now()->addDays(1),
            createdBy: 4
        );

        $result = $this->repository->create($invite);

        $this->assertNotNull($result->id);
        $this->assertGreaterThan(0, $result->id);
        $this->assertFalse($result->isUsed());
    }

    #[Test]
    public function it_can_mark_invite_as_used(): void
    {
        // Primero crear una invitación
        $invite = new ParentInvite(
            studentId: 5,
            email: 'used@example.com',
            token: 'token_789',
            expiresAt: Carbon::now()->addDays(2),
            createdBy: 6
        );
        $created = $this->repository->create($invite);

        // Marcar como usado
        $result = $this->repository->markAsUsed($created->id);

        $this->assertTrue($result);

        // Verificar que está marcado como usado
        $stub = $this->repository;
        $updatedInvite = $stub->getInvite($created->id);
        $this->assertNotNull($updatedInvite->usedAt);
        $this->assertTrue($updatedInvite->isUsed());
    }

    #[Test]
    public function mark_as_used_returns_false_for_nonexistent_invite(): void
    {
        $result = $this->repository->markAsUsed(999); // ID que no existe

        $this->assertFalse($result);
    }

    #[Test]
    public function mark_as_used_returns_false_when_already_used(): void
    {
        $stub = new ParentInviteRepStub();

        // Crear invitación ya usada
        $invite = new ParentInvite(
            studentId: 7,
            email: 'already@example.com',
            token: 'token_101',
            expiresAt: Carbon::now()->addDays(3),
            createdBy: 8,
            usedAt: Carbon::now()->subHours(1)
        );
        $created = $stub->create($invite);

        // Intentar marcar como usado de nuevo
        $result = $stub->markAsUsed($created->id);

        // Depende de la implementación, podría ser true o false
        $this->assertIsBool($result);
    }

    #[Test]
    public function it_can_delete_expired_invites(): void
    {
        $result = $this->repository->deleteExpired();

        $this->assertIsInt($result);
        $this->assertGreaterThanOrEqual(0, $result);
    }

    #[Test]
    public function delete_expired_only_removes_expired_invites(): void
    {
        $stub = new ParentInviteRepStub();

        // Agregar algunas invitaciones
        $expired = new ParentInvite(
            studentId: 9,
            email: 'expired@example.com',
            token: 'token_202',
            expiresAt: Carbon::now()->subDays(1), // Expirada
            createdBy: 10
        );
        $stub->addInvite($expired);

        $notExpired = new ParentInvite(
            studentId: 11,
            email: 'valid@example.com',
            token: 'token_303',
            expiresAt: Carbon::now()->addDays(5), // No expirada
            createdBy: 12
        );
        $stub->addInvite($notExpired);

        $countBefore = $stub->getInvitesCount();
        $deleted = $stub->deleteExpired();
        $countAfter = $stub->getInvitesCount();

        $this->assertGreaterThan(0, $deleted);
        $this->assertEquals($countBefore - $deleted, $countAfter);
    }

    #[Test]
    public function it_handles_database_errors_gracefully(): void
    {
        $stub = new ParentInviteRepStub();
        $stub->shouldThrowDatabaseError(true);

        $invite = new ParentInvite(
            studentId: 13,
            email: 'error@example.com',
            token: 'token_404',
            expiresAt: Carbon::now()->addDays(1),
            createdBy: 14
        );

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Database error');

        $stub->create($invite);
    }

    #[Test]
    public function invite_can_be_expired(): void
    {
        $expiredInvite = new ParentInvite(
            studentId: 15,
            email: 'expired_test@example.com',
            token: 'token_505',
            expiresAt: Carbon::now()->subDays(2), // Expirada
            createdBy: 16
        );

        $stub = new ParentInviteRepStub();
        $stub->addInvite($expiredInvite);

        $this->assertTrue($expiredInvite->isExpired());
    }

    #[Test]
    public function invite_can_be_valid(): void
    {
        $validInvite = new ParentInvite(
            studentId: 17,
            email: 'valid_test@example.com',
            token: 'token_606',
            expiresAt: Carbon::now()->addDays(3), // Válida
            createdBy: 18
        );

        $stub = new ParentInviteRepStub();
        $stub->addInvite($validInvite);

        $this->assertFalse($validInvite->isExpired());
        $this->assertFalse($validInvite->isUsed());
    }
}
