<?php

namespace Tests\Unit\Domain\Repositories\Command;

use Tests\Stubs\Repositories\Command\PaymentMethodRepStub;
use Tests\Unit\Domain\Repositories\BaseRepositoryTestCase;
use App\Core\Domain\Repositories\Command\Payments\PaymentMethodRepInterface;
use App\Core\Domain\Entities\PaymentMethod;
use PHPUnit\Framework\Attributes\Test;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class PaymentMethodRepInterfaceTest extends BaseRepositoryTestCase
{
    /**
     * The interface class being implemented
     */
    protected string $interfaceClass = PaymentMethodRepInterface::class;

    /**
     * Setup the repository instance for testing
     */
    protected function setUp(): void
    {
        parent::setUp();

        // Usamos un stub para probar el contrato
        $this->repository = new PaymentMethodRepStub();
    }

    /**
     * Test que el repositorio puede ser instanciado
     */
    #[Test]
    public function it_can_be_instantiated(): void
    {
        $this->assertNotNull($this->repository, 'El repositorio no está inicializado');
        $this->assertImplementsInterface($this->interfaceClass);
    }

    /**
     * Test que todos los métodos requeridos existen
     */
    #[Test]
    public function it_has_all_required_methods(): void
    {
        $this->assertNotNull($this->repository, 'El repositorio no está inicializado');

        $methods = [
            'create',
            'delete'
        ];

        foreach ($methods as $method) {
            $this->assertMethodExists($method);
        }
    }

    #[Test]
    public function it_can_create_payment_method(): void
    {
        $paymentMethod = new PaymentMethod(
            user_id: 1,
            stripe_payment_method_id: 'pm_123456789',
            brand: 'Visa',
            last4: '4242',
            exp_month: 12,
            exp_year: 2027
        );

        $result = $this->repository->create($paymentMethod);

        $this->assertInstanceOf(PaymentMethod::class, $result);
        $this->assertEquals(1, $result->user_id);
        $this->assertEquals('pm_123456789', $result->stripe_payment_method_id);
        $this->assertEquals('Visa', $result->brand);
        $this->assertEquals('4242', $result->last4);
        $this->assertNotNull($result->id);
        $this->assertIsInt($result->id);
    }

    #[Test]
    public function created_payment_method_has_autogenerated_id(): void
    {
        $paymentMethod = new PaymentMethod(
            user_id: 2,
            stripe_payment_method_id: 'pm_987654321'
        );

        $result = $this->repository->create($paymentMethod);

        $this->assertNotNull($result->id);
        $this->assertGreaterThan(0, $result->id);
        $this->assertNull($result->brand); // No se especificó brand
    }

    #[Test]
    public function it_can_delete_payment_method(): void
    {
        // Primero crear un método de pago
        $paymentMethod = new PaymentMethod(
            user_id: 3,
            stripe_payment_method_id: 'pm_to_delete'
        );
        $created = $this->repository->create($paymentMethod);

        // Eliminar el método de pago
        $this->repository->delete($created->id);

        // Verificar que ya no existe
        $stub = $this->repository;
        $deletedMethod = $stub->getPaymentMethod($created->id);
        $this->assertNull($deletedMethod);
    }

    #[Test]
    public function delete_throws_exception_when_payment_method_not_found(): void
    {
        $paymentMethodId = 999; // ID que no existe

        $this->expectException(ModelNotFoundException::class);

        $this->repository->delete($paymentMethodId);
    }

    #[Test]
    public function payment_method_can_be_expired(): void
    {
        // Método de pago expirado
        $expiredPaymentMethod = new PaymentMethod(
            user_id: 4,
            stripe_payment_method_id: 'pm_expired',
            exp_month: 01,
            exp_year: 2020 // Expiró hace años
        );

        $this->assertTrue($expiredPaymentMethod->isExpired());
        $this->assertEquals('01/20', $expiredPaymentMethod->expirationDate());
    }

    #[Test]
    public function payment_method_can_be_valid(): void
    {
        // Método de pago válido
        $validPaymentMethod = new PaymentMethod(
            user_id: 5,
            stripe_payment_method_id: 'pm_valid',
            exp_month: 12,
            exp_year: (int) (date('Y') + 2) // Válido por 2 años más
        );

        $this->assertFalse($validPaymentMethod->isExpired());
        $this->assertNotNull($validPaymentMethod->expirationDate());
    }

    #[Test]
    public function payment_method_without_expiration_is_not_expired(): void
    {
        // Método de pago sin fecha de expiración (ej: OXXO)
        $paymentMethod = new PaymentMethod(
            user_id: 6,
            stripe_payment_method_id: 'pm_no_exp'
        );

        $this->assertFalse($paymentMethod->isExpired());
        $this->assertEquals('N/A', $paymentMethod->expirationDate());
    }

    #[Test]
    public function payment_method_can_have_masked_card(): void
    {
        $paymentMethod = new PaymentMethod(
            user_id: 7,
            stripe_payment_method_id: 'pm_with_last4',
            last4: '1234'
        );

        $this->assertEquals('**** **** **** 1234', $paymentMethod->getMaskedCard());
    }

    #[Test]
    public function payment_method_without_last4_returns_null_masked_card(): void
    {
        $paymentMethod = new PaymentMethod(
            user_id: 8,
            stripe_payment_method_id: 'pm_no_last4'
        );

        $this->assertNull($paymentMethod->getMaskedCard());
    }

    #[Test]
    public function it_handles_database_errors_gracefully(): void
    {
        $stub = new PaymentMethodRepStub();
        $stub->shouldThrowDatabaseError(true);

        $paymentMethod = new PaymentMethod(
            user_id: 9,
            stripe_payment_method_id: 'pm_error'
        );

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessage('Database error');

        $stub->create($paymentMethod);
    }

    #[Test]
    public function it_can_handle_multiple_operations(): void
    {
        $stub = new PaymentMethodRepStub();

        // 1. Crear método de pago
        $method1 = $stub->create(new PaymentMethod(1, 'pm_001'));
        $this->assertNotNull($method1->id);

        // 2. Crear otro método de pago
        $method2 = $stub->create(new PaymentMethod(1, 'pm_002', 'Mastercard', '5678'));
        $this->assertNotNull($method2->id);
        $this->assertNotEquals($method1->id, $method2->id);

        // 3. Eliminar el primero
        $stub->delete($method1->id);

        // 4. Verificar que el primero ya no existe
        $this->assertNull($stub->getPaymentMethod($method1->id));
        $this->assertNotNull($stub->getPaymentMethod($method2->id));
    }
}
