<?php

namespace App\Core\Domain\Enum\Exceptions;

/**
 * @OA\Schema(
 *     schema="ErrorCode",
 *     type="string",
 *     enum={
 *         "UNAUTHENTICATED",
 *         "ACCESS_TOKEN_EXPIRED",
 *         "FORBIDDEN",
 *         "DUPLICATE_ENTRY",
 *         "DATABASE_ERROR",
 *         "NOT_FOUND",
 *         "INVALID_ARGUMENT",
 *         "CARD_ERROR",
 *         "RATE_LIMIT_EXCEEDED",
 *         "TOO_MANY_REQUESTS",
 *         "STRIPE_API_ERROR",
 *         "VALIDATION_ERROR",
 *         "INTERNAL_SERVER_ERROR",
 *         "STRIPE_GATEWAY_ERROR",
 *         "CONCEPT_ALREADY_ACTIVE",
 *         "CONCEPT_ALREADY_DELETED",
 *         "CONCEPT_ALREADY_DISABLED",
 *         "CONCEPT_ALREADY_FINALIZED",
 *         "CONCEPT_APPLIES_TO_CONFLICT",
 *         "CONCEPT_CANNOT_BE_DISABLED",
 *         "CONCEPT_CANNOT_BE_FINALIZED",
 *         "CONCEPT_CANNOT_BE_UPDATED",
 *         "REMOVE_EXCEPTIONS_AND_EXCEPTION_STUDENT_OVERLAP",
 *         "CONCEPT_CONFLICT_STATUS",
 *         "PAYMENT_ALREADY_EXISTS",
 *         "PROMOTION_ALREADY_EXECUTED",
 *         "RELATION_ALREADY_EXISTS",
 *         "STUDENTS_AND_EXCEPTIONS_OVERLAP",
 *         "USER_ALREADY_ACTIVE",
 *         "USER_ALREADY_DELETED",
 *         "USER_ALREADY_DISABLED",
 *         "USER_ALREADY_HAVE_STUDENT_DETAIL",
 *         "USER_CANNOT_BE_DISABLED",
 *         "USER_CANNOT_BE_UPDATED",
 *         "USER_CONFLICT_STATUS",
 *         "USER_EXPLICITLY_EXCLUDED",
 *         "ADMIN_ROLE_NOT_ALLOWED",
 *         "INVALID_CURRENT_PASSWORD",
 *         "INVALID_INVITATION",
 *         "PAYMENT_RETRY_NOT_ALLOWED",
 *         "PROMOTION_NOT_ALLOWED",
 *         "USER_INVALID_ROLE",
 *         "USER_NOT_ALLOWED",
 *         "CAREERS_NOT_FOUND",
 *         "CONCEPT_NOT_FOUND",
 *         "EXCEPTION_STUDENTS_NOT_FOUND",
 *         "PARENT_CHILDREN_NOT_FOUND",
 *         "PAYMENT_METHOD_NOT_FOUND",
 *         "PAYMENT_NOT_FOUND",
 *         "PERMISSION_NOT_FOUND",
 *         "PERMISSIONS_BY_USER_NOT_FOUND",
 *         "RECIPIENTS_NOT_FOUND",
 *         "ROLE_NOT_FOUND",
 *         "STUDENT_DETAIL_NOT_FOUND",
 *         "STUDENTS_NOT_FOUND",
 *         "USER_NOT_FOUND",
 *          "STUDENT_PARENTS_NOT_FOUND",
 *         "USERS_NOT_FOUND_FOR_UPDATE",
 *         "PAYMENT_NOTIFICATION_ERROR",
 *         "PAYMENT_RECONCILIATION_ERROR",
 *         "STRIPE_CHECKOUT_SESSION_ERROR",
 *         "INVALID_CREDENTIALS",
 *         "INVALID_REFRESH_TOKEN",
 *         "REFRESH_TOKEN_EXPIRED",
 *         "REFRESH_TOKEN_REVOKED",
 *         "USER_INACTIVE",
 *         "APPLICANT_TAG_INVALID",
 *         "CAREER_SEMESTER_INVALID",
 *         "CONCEPT_END_DATE_BEFORE_START",
 *         "CONCEPT_END_DATE_BEFORE_TODAY",
 *         "CONCEPT_END_DATE_TOO_FAR",
 *         "CONCEPT_EXPIRED",
 *         "CONCEPT_INACTIVE",
 *         "CONCEPT_INVALID_AMOUNT",
 *         "CONCEPT_INVALID_END_DATE",
 *         "CONCEPT_INVALID_START_DATE",
 *         "CONCEPT_MISSING_NAME",
 *         "CONCEPT_NOT_STARTED",
 *         "CONCEPT_START_DATE_TOO_EARLY",
 *         "CONCEPT_START_DATE_TOO_FAR",
 *         "PAYMENT_METHOD_NOT_SUPPORTED",
 *         "SEMESTERS_NOT_FOUND",
 *         "PAYOUT_VALIDATION",
 *         "REQUIRED_FOR_APPLIES_TO",
 *          "METHOD_NOT_ALLOWED",
 *          "PAYLOAD_TOO_LARGE",
 *          "SERVICE_UNAVAILABLE"
 *     },
 *     description="Códigos de error estandarizados del sistema",
 *     example="VALIDATION_ERROR"
 * )
 *
 *
 */
enum ErrorCode:string
{
    // ========== DEL HANDLER ==========
    case UNAUTHENTICATED = 'UNAUTHENTICATED';
    case ACCESS_TOKEN_EXPIRED = 'ACCESS_TOKEN_EXPIRED';
    case FORBIDDEN = 'FORBIDDEN';
    case DUPLICATE_ENTRY = 'DUPLICATE_ENTRY';
    case DATABASE_ERROR = 'DATABASE_ERROR';
    case NOT_FOUND = 'NOT_FOUND';  // ModelNotFoundException
    case BAD_REQUEST = 'BAD_REQUEST';
    case INVALID_ARGUMENT = 'INVALID_ARGUMENT';
    case CARD_ERROR = 'CARD_ERROR';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
    case TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS';
    case STRIPE_API_ERROR = 'STRIPE_API_ERROR';
    case VALIDATION_ERROR = 'VALIDATION_ERROR';  // Illuminate\Validation\ValidationException
    case INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';

    // ========== EXCEPCIONES EN RAÍZ ==========
    case STRIPE_GATEWAY_ERROR = 'STRIPE_GATEWAY_ERROR';

    // ========== CARPETA: Conflict (18) ==========
    case IDEMPOTENCY_EXISTS_EXCEPTION = 'IDEMPOTENCY_EXISTS_EXCEPTION';
    case IDEMPOTENCY_TIMEOUT_EXCEPTION = 'IDEMPOTENCY_TIMEOUT_EXCEPTION';
    case CONCEPT_ALREADY_ACTIVE = 'CONCEPT_ALREADY_ACTIVE';
    case CONCEPT_ALREADY_DELETED = 'CONCEPT_ALREADY_DELETED';
    case CONCEPT_ALREADY_DISABLED = 'CONCEPT_ALREADY_DISABLED';
    case CONCEPT_ALREADY_FINALIZED = 'CONCEPT_ALREADY_FINALIZED';
    case CONCEPT_APPLIES_TO_CONFLICT = 'CONCEPT_APPLIES_TO_CONFLICT';
    case CONCEPT_CANNOT_BE_DISABLED = 'CONCEPT_CANNOT_BE_DISABLED';
    case CONCEPT_CANNOT_BE_FINALIZED = 'CONCEPT_CANNOT_BE_FINALIZED';
    case CONCEPT_CANNOT_BE_UPDATED = 'CONCEPT_CANNOT_BE_UPDATED';
    case CONCEPT_CONFLICT_STATUS = 'CONCEPT_CONFLICT_STATUS';
    case PAYMENT_ALREADY_EXISTS = 'PAYMENT_ALREADY_EXISTS';
    case PROMOTION_ALREADY_EXECUTED = 'PROMOTION_ALREADY_EXECUTED';
    case RELATION_ALREADY_EXISTS = 'RELATION_ALREADY_EXISTS';
    case STUDENTS_AND_EXCEPTIONS_OVERLAP = 'STUDENTS_AND_EXCEPTIONS_OVERLAP';
    case USER_ALREADY_ACTIVE = 'USER_ALREADY_ACTIVE';
    case USER_ALREADY_DELETED = 'USER_ALREADY_DELETED';
    case USER_ALREADY_DISABLED = 'USER_ALREADY_DISABLED';
    case USER_ALREADY_HAVE_STUDENT_DETAIL = 'USER_ALREADY_HAVE_STUDENT_DETAIL';
    case USER_CANNOT_BE_DISABLED = 'USER_CANNOT_BE_DISABLED';
    case USER_CANNOT_BE_UPDATED = 'USER_CANNOT_BE_UPDATED';
    case USER_CONFLICT_STATUS = 'USER_CONFLICT_STATUS';
    case USER_EXPLICITLY_EXCLUDED = 'USER_EXPLICITLY_EXCLUDED';
    case REMOVE_EXCEPTIONS_AND_EXCEPTION_STUDENT_OVERLAP = 'REMOVE_EXCEPTIONS_AND_EXCEPTION_STUDENT_OVERLAP' ;

    // ========== CARPETA: NotAllowed (7) ==========
    case ADMIN_ROLE_NOT_ALLOWED = 'ADMIN_ROLE_NOT_ALLOWED';
    case INVALID_CURRENT_PASSWORD = 'INVALID_CURRENT_PASSWORD';
    case INVALID_INVITATION = 'INVALID_INVITATION';
    case PAYMENT_RETRY_NOT_ALLOWED = 'PAYMENT_RETRY_NOT_ALLOWED';
    case PROMOTION_NOT_ALLOWED = 'PROMOTION_NOT_ALLOWED';
    case USER_INVALID_ROLE = 'USER_INVALID_ROLE';
    case USER_NOT_ALLOWED = 'USER_NOT_ALLOWED';
    case NOT_ALLOWED = 'NOT_ALLOWED';

    // ========== CARPETA: NotFound (14) ==========
    case CAREERS_NOT_FOUND = 'CAREERS_NOT_FOUND';
    case CONCEPT_NOT_FOUND = 'CONCEPT_NOT_FOUND';
    case EXCEPTION_STUDENTS_NOT_FOUND = 'EXCEPTION_STUDENTS_NOT_FOUND';
    case PARENT_CHILDREN_NOT_FOUND = 'PARENT_CHILDREN_NOT_FOUND';
    case PAYMENT_METHOD_NOT_FOUND = 'PAYMENT_METHOD_NOT_FOUND';
    case PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND';
    case PERMISSION_NOT_FOUND = 'PERMISSION_NOT_FOUND';
    case PERMISSIONS_BY_USER_NOT_FOUND = 'PERMISSIONS_BY_USER_NOT_FOUND';
    case RECIPIENTS_NOT_FOUND = 'RECIPIENTS_NOT_FOUND';
    case ROLE_NOT_FOUND = 'ROLE_NOT_FOUND';
    case STUDENT_DETAIL_NOT_FOUND = 'STUDENT_DETAIL_NOT_FOUND';
    case STUDENTS_NOT_FOUND = 'STUDENTS_NOT_FOUND';
    case USER_NOT_FOUND = 'USER_NOT_FOUND';
    case USERS_NOT_FOUND_FOR_UPDATE = 'USERS_NOT_FOUND_FOR_UPDATE';
    case STUDENT_PARENTS_NOT_FOUND = 'STUDENT_PARENTS_NOT_FOUND';

    // ========== CARPETA: ServerError (3) ==========
    case PAYMENT_NOTIFICATION_ERROR = 'PAYMENT_NOTIFICATION_ERROR';
    case PAYMENT_RECONCILIATION_ERROR = 'PAYMENT_RECONCILIATION_ERROR';
    case STRIPE_CHECKOUT_SESSION_ERROR = 'STRIPE_CHECKOUT_SESSION_ERROR';

    // ========== CARPETA: Unauthorized (5) ==========
    case INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
    case INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN';
    case REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED';
    case REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED';
    case USER_INACTIVE = 'USER_INACTIVE';

    // ========== CARPETA: Validation (16) ==========
    case APPLICANT_TAG_INVALID = 'APPLICANT_TAG_INVALID';
    case CAREER_SEMESTER_INVALID = 'CAREER_SEMESTER_INVALID';
    case CONCEPT_END_DATE_BEFORE_START = 'CONCEPT_END_DATE_BEFORE_START';
    case CONCEPT_END_DATE_BEFORE_TODAY = 'CONCEPT_END_DATE_BEFORE_TODAY';
    case CONCEPT_END_DATE_TOO_FAR = 'CONCEPT_END_DATE_TOO_FAR';
    case CONCEPT_EXPIRED = 'CONCEPT_EXPIRED';
    case CONCEPT_INACTIVE = 'CONCEPT_INACTIVE';
    case CONCEPT_INVALID_AMOUNT = 'CONCEPT_INVALID_AMOUNT';
    case CONCEPT_INVALID_END_DATE = 'CONCEPT_INVALID_END_DATE';
    case CONCEPT_INVALID_START_DATE = 'CONCEPT_INVALID_START_DATE';
    case CONCEPT_MISSING_NAME = 'CONCEPT_MISSING_NAME';
    case CONCEPT_NOT_STARTED = 'CONCEPT_NOT_STARTED';
    case CONCEPT_START_DATE_TOO_EARLY = 'CONCEPT_START_DATE_TOO_EARLY';
    case CONCEPT_START_DATE_TOO_FAR = 'CONCEPT_START_DATE_TOO_FAR';
    case PAYMENT_METHOD_NOT_SUPPORTED = 'PAYMENT_METHOD_NOT_SUPPORTED';
    case SEMESTERS_NOT_FOUND = 'SEMESTERS_NOT_FOUND';
    case PAYOUT_VALIDATION = 'PAYOUT_VALIDATION';
    case REQUIRED_FOR_APPLIES_TO = 'REQUIRED_FOR_APPLIES_TO';
    CASE PAYMENT_IS_NOT_PAID = 'PAYMENT_IS_NOT_PAID';

    // ========== Otros ==========
    case METHOD_NOT_ALLOWED = 'METHOD_NOT_ALLOWED';
    case PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE';
    case SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE';


}
